# Generated by Django 5.0.4 on 2026-05-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_country_userprofile_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificates',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contributions',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='day_streak',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_time_hours',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='CET (UTC+1)', max_length=100),
        ),
    ]
