# Generated by Django 5.0.4 on 2026-06-11 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Write your article here using Markdown formatting.')),
                ('image', models.ImageField(blank=True, help_text='Cover image for the news article.', null=True, upload_to='news_images/')),
                ('source_name', models.CharField(blank=True, help_text='e.g., WADA, Quora, Twitter', max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='Original link to the news source')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
